[theme]
# This sets the base theme to light for all Streamlit components
base = "light"

# These colors align any default Streamlit elements with your UW brand
primaryColor = "#4B2E83"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#EFEAF8"
textColor = "#31261D"
font = "sans serif"
