#!/usr/bin/env python3
"""Opt-in real browser/backend acceptance using only in-memory synthetic fixtures.

Run with EPHEMERAL_UI_URL set to an isolated candidate. No prompts/responses, traces,
content screenshots or uploaded fixture files are written to disk.
"""
import io
import os

from PIL import Image, ImageDraw, ImageFont
from playwright.sync_api import expect, sync_playwright

URL = os.environ['EPHEMERAL_UI_URL']


def synthetic_scan(format_name):
    image = Image.new('RGB', (900, 220), 'white')
    draw = ImageDraw.Draw(image)
    font = ImageFont.load_default(size=48)
    draw.text((30, 60), 'Fictional beacon code: 731', fill='black', font=font)
    with io.BytesIO() as out:
        image.save(out, format=format_name)
        return out.getvalue()


def input_box(page):
    return page.get_by_test_id('stChatInputTextArea')


def ready(page):
    expect(input_box(page)).to_be_enabled(timeout=240_000)


def submit(page, text, files=None):
    ready(page)
    if files:
        page.locator('input[type=file]').set_input_files(files)
        for item in files:
            expect(page.get_by_text(item['name'], exact=True).first).to_be_visible()
    input_box(page).fill(text)
    page.get_by_test_id('stChatInputSubmitButton').click()


def answer(page, value):
    expect(page.locator('[class*="st-key-assistant-"] [data-testid="stMarkdownContainer"]').filter(has_text=value).last).to_be_visible(timeout=240_000)
    ready(page)
    assert page.get_by_test_id('stException').count() == 0


def reset(page):
    page.get_by_role('button', name='New Chat', exact=True).click()
    expect(page.locator('section.welcome-shell')).to_be_visible(timeout=20_000)
    ready(page)


def main():
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        first, second = browser.new_context(), browser.new_context()
        a, b = first.new_page(), second.new_page()
        a.goto(URL); b.goto(URL)
        expect(a.locator('section.welcome-shell')).to_be_visible(timeout=20_000)
        expect(b.locator('section.welcome-shell')).to_be_visible(timeout=20_000)
        submit(b, 'Remember this fictional label: SESSION-B-482. Reply with that label only.')
        answer(b, 'SESSION-B-482')
        submit(a, 'What is the fictional beacon code? Reply with the number only.', [
            {'name': 'beacon.txt', 'mimeType': 'text/plain', 'buffer': b'Fictional beacon code: 731.'}])
        answer(a, '731')
        assert 'available' in a.locator('.attachment-meta').inner_text()
        print('PASS real TXT upload -> Tika -> model -> browser', flush=True)
        # Copy/export are generated by the app; inspect only synthetic content.
        copy_frames = [f for f in a.frames if f != a.main_frame and 'Copy Conversation' in f.locator('body').inner_text()]
        assert copy_frames
        copied = copy_frames[0].evaluate('''() => { window.__copied = null; window.ClipboardItem = class {constructor(data) {this.data=data;} async getType(type) {return this.data[type];}};
            Object.defineProperty(navigator, 'clipboard', {configurable:true, value:{
              write: async items => {window.__copied=await (await items[0].getType('text/plain')).text();},
              writeText: async text => {window.__copied=text;}}}); return true; }''')
        assert copied
        copy_frames[0].get_by_role('button').click()
        copy_frames[0].wait_for_function('window.__copied !== null')
        exported = copy_frames[0].evaluate('window.__copied')
        assert '731' in exported and 'beacon.txt' in exported and 'available' in exported
        print('PASS copy/export (browser clipboard API intercepted with in-memory sink)', flush=True)
        reset(a)
        assert 'SESSION-B-482' in b.locator('body').inner_text()
        assert 'SESSION-B-482' not in a.locator('body').inner_text()
        assert 'beacon.txt' not in b.locator('body').inner_text()
        submit(a, 'What number is in the image? Reply with the number only.', [
            {'name': 'beacon.png', 'mimeType': 'image/png', 'buffer': synthetic_scan('PNG')}])
        answer(a, '731')
        print('PASS real supported-image -> model -> browser', flush=True)
        reset(a)
        submit(a, 'What is the beacon code in the scanned page? Reply with the number only.', [
            {'name': 'scan.pdf', 'mimeType': 'application/pdf', 'buffer': synthetic_scan('PDF')}])
        answer(a, '731')
        print('PASS real scanned PDF -> Tika OCR -> model -> browser', flush=True)
        reset(a)
        # Empty content has an observable parser outcome without provoking shared failures.
        submit(a, '', [{'name': 'empty.txt', 'mimeType': 'text/plain', 'buffer': b' \n\t'}])
        expect(a.get_by_text('No attachment content was available', exact=False)).to_be_visible(timeout=60_000)
        ready(a)
        submit(a, 'Was any readable content available in the file?')
        expect(a.locator('[class*="st-key-assistant-"]')).to_have_count(2, timeout=120_000)
        ready(a)
        assert 'unavailable' in a.locator('.attachment-meta').inner_text()
        print('PASS real unreadable upload and follow-up status', flush=True)
        reset(a)
        a.get_by_text('Thinking Mode', exact=True).click()
        expect(a.get_by_role('checkbox', name='Thinking Mode', exact=True)).to_be_checked()
        submit(a, 'Reply with only the number 5.')
        answer(a, '5')
        expect(a.get_by_role('checkbox', name='Thinking Mode', exact=True)).not_to_be_checked()
        submit(a, 'Reply with only the number 6.')
        answer(a, '6')
        print('PASS one-turn Thinking Mode browser reset', flush=True)
        assert 'SESSION-B-482' in b.locator('body').inner_text()
        print('PASS two isolated browser sessions', flush=True)
        first.close(); second.close(); browser.close()


if __name__ == '__main__':
    main()
